### ISSUE TITLE
Missing error for lack of version_value.

### ISSUE THREAD

**Issue by EvansJonathan** [Vulnogram/Vulnogram#13] opened 2018-04-16 16:53 UTC
The JSON format (https://github.com/CVEProject/automation-working-group/blob/master/cve_json_schema/CVE_JSON_4.0_min_public.schema) requires at least one version_value field be present.  When using https://vulnogram.github.io/, I am not notified if I fail to include this value.

This is likely the cause of the errors in https://github.com/CVEProject/cvelist/pull/419 and https://github.com/CVEProject/cvelist/pull/417.

**Comment by chandanbn** [comment] 2018-04-17 22:25
This is now fixed in https://vulnogram.github.io/. 

Root cause:
An empty string (`version_value: ""`) would have satisfied the` "required": ["version_value"]` rule, and would not have throw an error. When the JSON was optimized on JSON tab, the field itself was removed. I had to add a `"minLength": 1` attribute to schema for `version_value` to fix it.

I should validated the JSON again after it is optimized and before it is downloaded.

**Closed by chandanbn** 2018-04-17 22:25 UTC
