### ISSUE TITLE
in 0.1.0, cveLogin requests /api/org/ with some web browsers

### ISSUE THREAD

**Issue by ElectricNroff** [Vulnogram/Vulnogram#58] opened 2022-03-02 20:35 UTC
The "CVE Login" button seems to work fine with Firefox. With Chrome and Edge, even if the user has never previously visited the https://vulnogram.github.io/cve5 website and enters credentials for the first time, login fails with an "Error logging in: SECRETARIAT_ONLY" message. The browser (Chrome or Edge) is sending a GET request for the https://cveawg-test.mitre.org/api/org/ URL. Presumably it was supposed to be sending /api/org/ followed by the short name of the CNA, not /api/org/ alone. The use of /api/org/ occurs with released Chrome/Edge versions and even with the latest hourly Chromium build (version 101.0.4921.0 for 64-bit Windows).

**Comment by chandanbn** [comment] 2022-03-03 19:05
I believe this got addressed by https://github.com/Vulnogram/Vulnogram/commit/f9d7b1f9ce17a5b1e81442408bce4801c5b7a4bc
When did you notice this?

I couldn't reproduce this. However the login/logout workflow needs improvements see #56

**Comment by ElectricNroff** [comment] 2022-03-11 18:37
Actually, I think that commit is what introduced the login problem.

The top-level branching on authorization is
https://github.com/Vulnogram/Vulnogram/blob/f9d7b1f9ce17a5b1e81442408bce4801c5b7a4bc/default/cve5/cve.js#L198-L202
in which PasswordCredential is supported by Chrome and Edge, but not by Firefox:
https://developer.mozilla.org/en-US/docs/Web/API/PasswordCredential#browser_compatibility

So, Chrome does:
https://github.com/Vulnogram/Vulnogram/blob/f9d7b1f9ce17a5b1e81442408bce4801c5b7a4bc/default/cve5/cve.js#L269-L278
However,
https://github.com/Vulnogram/Vulnogram/blob/f9d7b1f9ce17a5b1e81442408bce4801c5b7a4bc/default/cve5/cve.js#L339-L343

and thus apparently the intention was
```
let [user, org] = cred.name.split("|");
```
cred.id.split("|") is setting org to the portion of the "cve-services" string after the first '|' character. Thus, org is always empty, and:
https://github.com/Vulnogram/Vulnogram/blob/f9d7b1f9ce17a5b1e81442408bce4801c5b7a4bc/default/cve5/cve.js#L112-L115
constructs a /api/org/ URL (an endpoint available only to the Secretariat) instead of the intended /api/org/\_SHORT_NAME_OF_THE_CNA\_ endpoint. Therefore, a Chrome or Edge login attempt can fail with:
```
SECRETARIAT_ONLY
This function is currently only allowed to the Secretariat. This will change for many functions as more administrative roles are implemented.
```
This affected one small CNA that tried using https://vulnogram.github.io/cve5 for CVE ID reservation in production today. Production use has otherwise been infrequent, so it hasn't been presenting a huge problem.

Using Firefox is apparently a complete workaround. None of the navigator.credentials.* code is reachable from Firefox and the other browsers that lack support for the PasswordCredential interface in https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API @chandanbn

**Comment by chandanbn** [comment] 2022-03-11 18:56
The [cve.js](https://github.com/xdrr/cve.js) library tries to do both credentials management and talk to CVE services. IMHO the reliance on credential management API may be an overkill. We will have to separate that out from the library but ensure CVE credentials are as securely handled as possible (until we have some sort of session management available in the services itself).

**Comment by chandanbn** [comment] 2022-04-15 02:40
Fixed in cve-session branch.

**Closed** 2022-04-15 02:41 UTC
